title: "My Dashboard"
theme:
  name: dark
  primary-color: 217 79 45
  secondary-color: 207 77 65
  background-color: 210 17 12
  card-background-color: 220 13 20

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: to-do


          - type: weather
            location: "Charlotte, United States"
            latitude: 35.22709
            longitude: -80.84313
            units: imperial
            hour-format: 12h

          - type: repository
            repository: jmstew3/json-schema-generator
            pull-requests-limit: 5
            issues-limit: 3
            commits-limit: 3

      - size: full
        widgets:
          - type: docker-containers
            show-stopped: true
          
          - type: server-stats
            include-docker: true

          - type: group
            widgets:
              - type: reddit
                subreddit: cursor
              - type: reddit
                subreddit: SaaS
                show-thumbnails: true
              - type: reddit
                subreddit: ClaudeAI
                show-thumbnails: true

      - size: small
        widgets:
          - type: clock
            timezone: "local"
            hour-format: 12h

          - type: bookmarks
            groups:
              - links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    url: https://www.amazon.com/
                  - title: Github
                    url: https://github.com/
                  - title: Wikipedia
                    url: https://en.wikipedia.org/
              - title: Entertainment
                color: 10 70 50
                links:
                  - title: OpenAI
                    url: https://www.openai.com
                  - title: Disney+
                    url: https://www.disneyplus.com/
                  - title: YouTube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    url: https://www.primevideo.com/
              - title: Social
                color: 200 50 50
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                  - title: Twitter
                    url: https://twitter.com/
                  - title: Instagram
                    url: https://www.instagram.com/
